
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9000:9000"  # Expose backend for internal communication
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./nao_backend.db
      - OPENAI_API_KEY_NAO_ROBOT=${OPENAI_API_KEY_NAO_ROBOT}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_URL=${WEATHER_API_URL}
      - NEWS_API_KEY=${NEWS_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8090:8090"  # Serve static files directly

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "90:90"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom Nginx config
    depends_on:
      - frontend
      - backend
    restart: always # Restart Nginx if it fails